services:
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9092:9090"  # Port modifié pour éviter les conflits
    volumes:
      - ./my-new-app/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3001:3000"  # Port modifié pour Grafana
    restart: unless-stopped
    volumes:
      - ./my-new-app/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
