scrape_configs:
  - job_name: 'MyNewAppMetrics'
    metrics_path: '/custom/metrics'  
    scrape_interval: 5s            
    static_configs:
      - targets: ['my-new-app.local:8083']  
        labels:
          application: 'My New Spring Boot App'  
